# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmrEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('amr', models.CharField(max_length=5000)),
                ('reference_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_sentence', models.CharField(max_length=1000)),
                ('amr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amr.AmrEntry')),
            ],
        ),
    ]
